[package]
name = "cracker"
include = ["src/**/*", "README.md"]
default-run = "ck"
version = "0.3.0"
edition = "2021"
license = "GPL-3.0"
description = "Cracker is a simple, fast, and plain task runner. Designed with the idea of supporting as many task tools as possible."
authors = ["Lloyd Bond"]

[[bin]]
name = "ck"
path = "src/main.rs"

[dependencies]
iced = {version = "0.13.1", features = ["debug", "tokio", "highlighter", "lazy"]}
itertools = "0.13.0"
once_cell = "1.20.2"
peg = "0.8.4"
rfd = "0.15.0"
tokio = {version = "1", features = ["fs", "io-util"]}
